# introspection in pygoject3 conflicts with introspection in pygobject
# https://bugzilla.gnome.org/show_bug.cgi?id=657054
if is_depends_enabled pygobject gobject-introspection; then
  up_trigger pygobject cast_self
fi
